    setSelectedCompany(next);
    setExchangeCompany(next);
    setTab("exchange");
  };

  return <div className="game-shell">
    <header className="game-topbar">
      <button className="game-brand" onClick={()=>setTab("overview")} aria-label="MarketArena"><img src="/marketarena-logo.svg" alt="MarketArena"/></button>
      <div className="topbar-context"><span>ECONOMIC WORLD</span><b>{country.name}</b><em>DAY {day}</em></div>
      <div className="game-right">
        <div className="topbar-time-controls">
          <button type="button" className={timePaused?"time-main paused":"time-main"} onClick={()=>setTimePaused(v=>!v)}>{timePaused?"▶":"Ⅱ"} <span>{timePaused?"Продолжить":"Пауза"}</span></button>
          <div className="time-speed-group">{[1,1.5,2].map(x=><button type="button" key={x} className={timeSpeed===x?"active":""} onClick={()=>{setTimePaused(false);setTimeSpeed(x as 1|1.5|2)}}>×{x}</button>)}</div>
        </div>
        <div className="topbar-wealth"><span>NET WORTH</span><b>{totalWealth.toLocaleString("ru-RU")} VLR</b></div>
        <button className="topbar-next" onClick={advance}>Следующий день <b>→</b></button>
      </div>
    </header>
    <div className="game-body">
      <aside className="game-sidebar">
        <div className="sidebar-player"><div className="sidebar-avatar">{player.trim().slice(0,1).toUpperCase()}</div><div><b>{player}</b><small>Ур. {careerLevel} · {careerTitle}</small></div></div>
        <div className="sidebar-section"><span>COMMAND</span>{tabs.slice(0,8).map(([id,label])=><button type="button" key={id} className={tab===id?"active":""} onClick={()=>id==="exchange"?openExchange():setTab(id)}><span className="nav-glyph"><NavIcon id={id}/></span>{label}{id==="overview"&&<em>HOME</em>}{id==="map"&&<em>WORLD</em>}</button>)}</div>
        <div className="sidebar-section"><span>INTELLIGENCE</span>{tabs.slice(8).map(([id,label])=><button type="button" key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><span className="nav-glyph"><NavIcon id={id}/></span>{label}</button>)}</div>
        <div className="sidebar-next"><span>NEXT MOVE</span><b>{campaignGoals.find(g=>!g.done)?.title ?? "Новая цель"}</b><small>{campaignGoals.find(g=>!g.done)?.text ?? "Продолжай развивать империю."}</small><button onClick={()=>setTab(campaignGoals.find(g=>!g.done)?.id==="first-job"?"life":"profile")}>Открыть цель →</button></div>
        <div className="sidebar-status"><span>MARKET STATUS</span><b className={currentCrisis?"loss":"gain"}>{currentCrisis?currentCrisis.name:"Рынок стабилен"}</b><small>Влияние {Math.min(100,countryInfluence+ownedCompanies.length*18)}/100</small></div>
      </aside>
            <main className="game-main">
        {tab==="overview"&&<><div className="game-heading"><div><span className="eyebrow">ДЕНЬ {day} · {country.name.toUpperCase()}</span><h1>{country.name}: экономический центр</h1><p>{notice}</p></div><button className="day-button" onClick={advance}>Следующий день →</button></div>
          <section className="empire-roadmap"><div className="empire-roadmap-head"><div><span className="eyebrow">ГЛОБАЛЬНАЯ ЦЕЛЬ</span><h2>Построй экономическую империю</h2><p>Начни с работы и резерва, затем покупай акции, используй кредит только под понятную сделку, переживай кризисы и набирай влияние. На 51% начинается контроль компании; после нескольких контролируемых активов формируется холдинг.</p></div><div className="empire-score"><b>{Math.min(100,countryInfluence+ownedCompanies.length*18)}</b><span>ВЛИЯНИЕ</span></div></div><div className="empire-steps"><div className="empire-step"><b>01</b><strong>Капитал</strong><span>Работа → резерв → первые инвестиции.</span></div><div className="empire-step"><b>02</b><strong>Влияние</strong><span>Покупай акции, изучай новости и формируй позиции.</span></div><div className="empire-step"><b>03</b><strong>Контроль 51%</strong><span>Контрольный пакет = компания входит в твою группу.</span></div><div className="empire-step"><b>04</b><strong>Группа</strong><span>Расширяй холдинг и готовься к следующим рынкам.</span></div></div><div className="empire-how"><span><b>Акция</b> — доля собственности и рыночная позиция.</span><span><b>Контроль 51%</b> — отдельное поглощение по капитализации с премией.</span><span><b>Влияние</b> — показатель силы игрока, растущий через капитал, карьеру и контроль.</span></div></section>
          <div className="hero-map-grid">
            <section className="market-map-card"><div className="card-head"><div><span>РЕЛЬЕФ · ЭКОНОМИКА · КОМПАНИИ</span><h2>Карта {country.name}</h2></div><b className="positive">{priceChange(country.companies[0])>=0?"+":""}{priceChange(country.companies[0]).toFixed(2)}%</b></div><AtlasMap selected={country.id} onSelect={()=>{}} showCompanies onCompany={openExchange}/></section>
            <section className="capital-card"><span>ОБЩИЙ КАПИТАЛ</span><strong>{totalWealth.toLocaleString("ru-RU")} VLR</strong><small>Свободные деньги · {cash.toLocaleString("ru-RU")} VLR</small><div className="money-bar"><i style={{width:cashPct+"%"}}/></div><div className="capital-actions"><button onClick={()=>setTab("life")}>Заработать</button><button onClick={()=>openExchange()}>Инвестировать</button></div></section>
            <section className="jobs-card"><div className="card-head"><div><span>РАБОТА И ДОХОД</span><h2>Заработать на следующие сделки</h2></div><button onClick={()=>setTab("life")}>Все →</button></div>{jobs.map(j=><div className="job-row" key={j.id}><div><b>{j.title}</b><small>{j.time} · {j.text}</small></div><button disabled={jobCooldown===j.id} onClick={()=>startJobGame(j.id)}>+{j.pay.toLocaleString("ru-RU")} VLR</button></div>)}</section>
            <section className="campaign-card"><div className="card-head"><div><span>ГЛОБАЛЬНАЯ ЦЕЛЬ · 365 ДНЕЙ</span><h2>{campaignFinished?"Год завершён — твой результат":"Путь к экономической империи"}</h2></div><b>{completedGoals}/{campaignGoals.length}</b></div><p>{campaignFinished?"Кампания остановлена. Теперь важен не только капитал, но и то, сколько компаний ты контролируешь и какой риск выдержал.":"Работа → капитал → кредит → риск → контроль компаний. Не обязательно быть самым богатым — нужно построить устойчивую экономическую группу."}</p><div className="campaign-progress"><i style={{width:(completedGoals/campaignGoals.length*100)+"%"}}/></div><div className="campaign-stats"><div><span>ВЛИЯНИЕ</span><b>{Math.min(100,countryInfluence+ownedCompanies.length*18)}/100</b></div><div><span>КАРЬЕРА</span><b>Ур. {careerLevel}</b></div><div><span>ДЕНЬ</span><b>{day}/365</b></div></div><button className="campaign-open" onClick={()=>setTab("profile")}>Открыть цели →</button></section>
            <section className="risk-dashboard"><div><span>КРИЗИС / РИСК</span><h3>{currentCrisis?currentCrisis.name:"Рынок стабилен"}</h3><p>{currentCrisis?currentCrisis.short:"Следи за новостями: следующий системный шок может изменить условия кредита и котировки."}</p></div><strong className={currentCrisis?"loss":"gain"}>{currentCrisis?"−"+Math.round(Math.abs(currentCrisis.impact)*100)+"%":"НИЗКИЙ РИСК"}</strong></section>
            <section className="finance-card"><div><span>ФИНАНСИРОВАНИЕ</span><h2>Кредитный рычаг</h2><p>{loan?.balance?"Долг "+loan.balance.toLocaleString("ru-RU")+" VLR · 2,5% каждые 30 дней":"Используй долг только для сделки, которая может пережить кризис."}</p></div><div className="finance-actions">{loan?.balance?<><button onClick={()=>repayLoan(Math.min(loan.balance,100000))}>Погасить 100k</button><button onClick={()=>repayLoan(loan.balance)}>Погасить всё</button></>:<><button onClick={()=>takeLoan(Math.min(500000,loanLimit))} disabled={loanLimit<100000}>Взять 500k</button><button onClick={()=>takeLoan(1000000)} disabled={loanLimit<1000000}>Взять 1 млн</button></>}</div></section>
            <section className="companies-card"><div className="card-head"><div><span>ПУБЛИЧНЫЕ КОМПАНИИ</span><h2>Компании на карте {country.name}</h2></div><button onClick={()=>setTab("companies")}>Открыть все →</button></div><div className="ticker-grid">{country.companies.map(c=><button className="ticker-row" key={c.ticker} onClick={()=>openExchange(c)}><b>{c.ticker}</b><span>{c.name}<small>{c.sector}</small></span><em className="ticker-price">{priceFor(c).toLocaleString("ru-RU")} VLR</em><strong className={priceChange(c)>=0?"gain":"loss"}>{priceChange(c)>=0?"+":""}{priceChange(c).toFixed(2)}%</strong></button>)}</div></section>
          <section className="home-news-card"><div className="card-head"><div><span>ЛЕНТА РЫНКА · ДЕНЬ {day}</span><h2>Что происходит в экономике</h2></div><button onClick={()=>setTab("news")}>Все новости →</button></div><div className="home-news-list">{country.companies.slice(0,3).map(c=>{const e=marketEvent(c,day);return <button key={c.ticker} onClick={()=>setSelectedCompany(c)}><span className={e.impact>=0?"news-signal positive":"news-signal negative"}>{e.impact>=0?"▲":"▼"}</span><div><b>{c.name}</b><p>{e.headline}</p></div><strong className={e.impact>=0?"gain":"loss"}>{e.impact>=0?"+":""}{(e.impact*100).toFixed(1)}%</strong></button>})}</div></section>
          </div></>}